version: '3.6'
services:
  communicator:
    build: 
      context: ./communicator
      network: host
    environment:
      - GAME_MECHANICS_HOST=http://localhost:80
    ports:
      - "4000:4000"
    network_mode: host
  mechanics:
    build: 
      context: ./mechanics
      network: host
    ports:
      - "5000:80"
    network_mode: host
  frontend:
    build: 
      context: ./frontend
      network: host
    ports:
      - "8080:80"
