version: '3'
services:
  communicator:
    build: ./communicator
    environment:
      - GAME_MECHANICS_HOST=http://mechanics
    ports:
      - "4000:4000"
  mechanics:
    build: ./mechanics
    ports:
      - "5000:80"
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_HOST=ws://localhost:4000
    ports:
      - "8080:80"
