version: '3'
services:
  communicator:
    build: ./communicator
    environment:
      GAME_MECHANICS_HOST: http://mechanics
    ports:
      - "4000:4000"
    links:
      - mechanics
  mechanics:
    build: ./mechanics
    ports:
      - "5000:80"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
