name: Frontend deploy

on:
  push:
    branches:
      - master
      - feature/workflow
    paths:
      - 'frontend/**'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker context
        env:
          ssh_key: ${{ secrets.SSH_KEY }}
        run: |
          echo "$ssh_key" > ./deploy-key
          chmod 600 ./deploy-key
          docker context create aghtochess --docker "host=ssh://aghtochess@aghtochess.mionskowski.pl,key=$(pwd)/deploy_key"
      - name: Build and deploy
        id: deploy
        run: |
          docker-compose -f docker-compose.yml.production --context aghtochess up --build -d frontend
